apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aap
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Ansible Automation Platform GitOps Project

  # Only allow this specific Git repo
  sourceRepos:
    - 'https://github.com/CastawayEGR/aap-ocp-gitops.git'

  # Restrict destination namespaces
  destinations:
    - namespace: 'openshift-gitops'
      server: https://kubernetes.default.svc
    - namespace: 'aap'
      server: https://kubernetes.default.svc
    - namespace: 'aap-dev'
      server: https://kubernetes.default.svc
    - namespace: 'aap-staging'
      server: https://kubernetes.default.svc

  # No cluster-scoped resources - namespaces are pre-provisioned
  clusterResourceWhitelist: []

  # Explicitly whitelist only required namespaced resources
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
    - group: argoproj.io
      kind: AppProject
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: operators.coreos.com
      kind: OperatorGroup
    - group: operators.coreos.com
      kind: Subscription
    - group: aap.ansible.com
      kind: AnsibleAutomationPlatform
    - group: batch
      kind: Job
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding

  # Deny list - explicitly block dangerous resources
  clusterResourceBlacklist:
    - group: ''
      kind: Node
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  # Allow applications to sync to any namespace in the project
  roles:
    - name: admin
      description: Admin access to AAP project
      policies:
        - p, proj:aap:admin, applications, *, aap/*, allow
      groups:
        - aap-admins
